/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XsalgovicAmbulanceWlList {
    }
}
declare global {
    interface HTMLXsalgovicAmbulanceWlListElement extends Components.XsalgovicAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXsalgovicAmbulanceWlListElement: {
        prototype: HTMLXsalgovicAmbulanceWlListElement;
        new (): HTMLXsalgovicAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xsalgovic-ambulance-wl-list": HTMLXsalgovicAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XsalgovicAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xsalgovic-ambulance-wl-list": XsalgovicAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xsalgovic-ambulance-wl-list": LocalJSX.XsalgovicAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXsalgovicAmbulanceWlListElement>;
        }
    }
}
